name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Push Docker Images
        run:
            docker build -t misterfacile/fastapi-app:latest .
            docker push misterfacile/fastapi-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/scp-action@master
        with:
            host: 20.61.171.129
            username: ubuntu
            password: ${{ secrets.SERVER_PASSWORD }}
            source: "docker-compose.yml"
            target: "/home/ubuntu/paul.guan"
      - name: SSH Command to Restart Service
        uses: appleboy/ssh-action@master
        with:
            host: 20.61.171.129
            username: ubuntu
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              cd /home/ubuntu/paul.guan
              docker-compose down
              docker-compose up -d

      
        

